"""add a subscribers table

Revision ID: 1a61b967e9d5
Revises: b2fe7d767a22
Create Date: 2021-09-27 10:53:45.073210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a61b967e9d5'
down_revision = 'b2fe7d767a22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subs_email'), 'subs', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subs_email'), table_name='subs')
    op.drop_table('subs')
    # ### end Alembic commands ###
