"""added a bio,profile-pic-path and mobile phone section in the profile

Revision ID: 33e5fd1758fa
Revises: fd833799ec3b
Create Date: 2021-09-25 21:12:50.889048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33e5fd1758fa'
down_revision = 'fd833799ec3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('mobile', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('profile_pic_path', sa.String(length=200), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'profile_pic_path')
    op.drop_column('users', 'mobile')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
