"""add a blog table as well as a relationship with the user table

Revision ID: 60be1820bd41
Revises: 33e5fd1758fa
Create Date: 2021-09-26 07:12:27.855098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60be1820bd41'
down_revision = '33e5fd1758fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('meta_title', sa.String(length=200), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('posted', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blogs')
    # ### end Alembic commands ###
