"""add a name column to the subs table

Revision ID: 7c127a12e19b
Revises: 1a61b967e9d5
Create Date: 2021-09-27 11:02:55.283529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c127a12e19b'
down_revision = '1a61b967e9d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subs', sa.Column('name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subs', 'name')
    # ### end Alembic commands ###
